// <auto-generated />
using ECommerceBlazor.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceBlazor.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230419192746_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceBlazor.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "First product First product First product First product First product First product First product ",
                            ImageUrl = "https://www.notion.so/cdn-cgi/image/format=auto,width=3840,quality=100/https://images.ctfassets.net/spoqsaf9291f/4LkRwsdriDUzmpgR2QVCf7/95ebe8f6296bd68f14f0ae0291cb51c0/Productwiki.png",
                            Name = "First product",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Second Product Second Product Second Product Second Product Second Product Second Product Second Product Second Product Second Product Second Product ",
                            ImageUrl = "https://www.notion.so/cdn-cgi/image/format=auto,width=3840,quality=100/https://images.ctfassets.net/spoqsaf9291f/4LkRwsdriDUzmpgR2QVCf7/95ebe8f6296bd68f14f0ae0291cb51c0/Productwiki.png",
                            Name = "Second Product",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Third Product Third Product Third Product Third Product Third Product Third Product Third Product Third Product ",
                            ImageUrl = "https://www.notion.so/cdn-cgi/image/format=auto,width=3840,quality=100/https://images.ctfassets.net/spoqsaf9291f/4LkRwsdriDUzmpgR2QVCf7/95ebe8f6296bd68f14f0ae0291cb51c0/Productwiki.png",
                            Name = "Third Product ",
                            Price = 99.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
